// automatically generated by wsjcpp:v0.2.7

#include <wsjcpp_core.h>

class RES___src_resources_html_images_favicon_svg_pathc6e5e4 : public WsjcppResourceFile {
public:
  virtual const std::string &getFilename() const override;
  virtual const std::string &getPackAs() const override;
  virtual int getBufferSize() const override;
  virtual const char *getBuffer() const override;
};
